// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-dO0KiPAEj-CMj4r-MxJXEE9JqS05FY',
    appId: '1:809225926775:web:ee7e9681ddd5126d156e72',
    messagingSenderId: '809225926775',
    projectId: 'shoestore-89e72',
    authDomain: 'shoestore-89e72.firebaseapp.com',
    storageBucket: 'shoestore-89e72.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALU-f1FfIaO4nWB5zhKGNawu11AG86cB4',
    appId: '1:809225926775:android:84ca019bd31d2ece156e72',
    messagingSenderId: '809225926775',
    projectId: 'shoestore-89e72',
    storageBucket: 'shoestore-89e72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZLQFOqDmBgD_L2rlnMlFa3y0XT6lhV84',
    appId: '1:809225926775:ios:57648eb154f04d9d156e72',
    messagingSenderId: '809225926775',
    projectId: 'shoestore-89e72',
    storageBucket: 'shoestore-89e72.firebasestorage.app',
    iosBundleId: 'com.kodeco.yummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZLQFOqDmBgD_L2rlnMlFa3y0XT6lhV84',
    appId: '1:809225926775:ios:57648eb154f04d9d156e72',
    messagingSenderId: '809225926775',
    projectId: 'shoestore-89e72',
    storageBucket: 'shoestore-89e72.firebasestorage.app',
    iosBundleId: 'com.kodeco.yummy',
  );
}
